---
site_name: "LAB-1111: Optimizing Webex Suite for Control Hub Administrators" # This must begin with the session ID, e.g. LABXXX-1234 This is my Cisco Live Lab
site_description: "Optimizing Webex Suite for Control Hub Administrators" # must be same as "site_name"
site_author: Susan Parrish
copyright: Copyright &copy; 2025 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/LAB-1111.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
plugins:
  - search
  - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/Wx1_25_PDF_image.jpg
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Overview: overview.md
  - Lab activities:
    - Getting started: LabAccess.md
    - Lab 1 - Getting to know Control Hub: CHIntro.md
    - Lab 2 - First steps to optimization: FirstSteps.md
    - Lab 3 - Organization settings & template: OrganizationSettings.md
    - Lab 4 - Messaging : Messaging.md
    - Lab 5 - Meetings : Meetings.md
    - Lab 6 - Calling : Calling.md
    - Lab 7 - Vidcast: Vidcast.md
    - Lab 8 - Devices & workspaces: Devices.md
    - Lab 9 - User profiles: UserOverrides.md
    - Lab 10 - Alerts & analytics: Analytics.md
    - Congratulations!: Congratulations.md
  - That's a wrap!: conclusion.md

 